version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule: { interval: 'weekly', day: 'monday' }
    open-pull-requests-limit: 10
    groups:
      production-dependencies:
        dependency-type: 'production'
        labels: ['dependencies', 'security']
      development-dependencies:
        dependency-type: 'development'
        labels: ['dependencies']
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule: { interval: 'weekly' }
    labels: ['ci']
  - package-ecosystem: 'docker'
    directory: '/docker'
    schedule: { interval: 'weekly' }
    labels: ['docker']
